<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<jsp:include page="/view/admin/common/admin_layout_start.jsp"><jsp:param name="activeTab" value="returns"/></jsp:include>
<div class="admin-page">
    <%-- Các thông báo được controller lấy từ session rồi xoá sau khi hiển thị một lần. --%>
    <c:if test="${not empty successMsg}"><div class="d-none" data-admin-toast data-admin-toast-type="success"><c:out value="${successMsg}"/></div></c:if>
    <c:if test="${not empty errorMsg}"><div class="d-none" data-admin-toast data-admin-toast-type="error"><c:out value="${errorMsg}"/></div></c:if>

    <c:choose>
        <c:when test="${pageMode eq 'detail'}">
            <div class="page-header"><div><h1 class="page-title"><i class="fa-solid fa-rotate-left"></i>Return Request Details</h1><p class="subtext mt-1">Review the request, record returned products, and follow the refund workflow.</p></div><a class="btn btn-outline-secondary" href="${returnsBasePath}">Back to requests</a></div>
            <c:choose><c:when test="${empty returnRequest}"><div class="alert alert-danger">Return request not found.</div></c:when><c:otherwise>
                <div class="row g-4">
                    <div class="col-lg-8"><div class="card card-main mb-4"><div class="card-body p-4">
                        <div class="d-flex justify-content-between align-items-start gap-3 mb-3"><div><div class="text-muted small">REQUEST CODE</div><h2 class="h4 fw-bold mb-1">${returnRequest.requestCode}</h2><div class="text-muted">Order ${returnRequest.orderCode}</div></div><span class="badge rounded-pill text-bg-primary">${returnRequest.status}</span></div>
                        <div class="row g-3 mb-4"><div class="col-md-4"><div class="text-muted small">Customer</div><strong>${returnRequest.customerName}</strong></div><div class="col-md-4"><div class="text-muted small">Type</div><strong>${returnRequest.requestType}</strong></div><div class="col-md-4"><div class="text-muted small">Reason</div><strong>${returnRequest.reason}</strong></div></div>
                        <div class="table-responsive border rounded"><table class="table align-middle mb-0"><thead><tr><th>Product</th><th>Variant</th><th>Quantity</th><th>Unit price</th><th>Current stock</th></tr></thead><tbody><c:forEach var="item" items="${returnRequest.items}"><tr><td>${item.productNameSnapshot}</td><td>${item.variantAttributesSnapshot}</td><td>${item.quantity}</td><td><fmt:formatNumber value="${item.unitPrice}" pattern="#,##0"/> VND</td><td>${item.currentStock}</td></tr></c:forEach></tbody></table></div>
                        <div class="mt-4"><div class="text-muted small">CUSTOMER NOTE</div><div class="border rounded p-3 bg-light">${not empty returnRequest.customerNote ? returnRequest.customerNote : 'No additional information.'}</div></div>
                        <div class="mt-3"><div class="text-muted small">REFUND AMOUNT</div><div class="fs-4 fw-bold text-primary"><fmt:formatNumber value="${returnRequest.refundAmount}" pattern="#,##0"/> VND</div></div>
                    </div></div></div>
                    <div class="col-lg-4"><div class="card card-main"><div class="card-body p-4"><h3 class="h5 fw-bold mb-3">Available actions</h3>
                        <%-- Staff duyệt hồ sơ hoặc yêu cầu khách bổ sung thông tin. --%>
                        <c:if test="${returnRequest.status eq 'PENDING' or returnRequest.status eq 'INFO_REQUIRED'}"><form method="post" action="${returnsBasePath}" class="mb-2"><input type="hidden" name="action" value="review"><input type="hidden" name="status" value="APPROVED"><input type="hidden" name="id" value="${returnRequest.id}"><input type="hidden" name="returnMode" value="detail"><textarea name="note" class="form-control mb-2" rows="2" placeholder="Staff note (optional)"></textarea><button class="btn btn-success w-100" type="submit">Approve request</button></form><form method="post" action="${returnsBasePath}" class="mb-2"><input type="hidden" name="action" value="review"><input type="hidden" name="status" value="INFO_REQUIRED"><input type="hidden" name="id" value="${returnRequest.id}"><input type="hidden" name="returnMode" value="detail"><input type="hidden" name="note" value="Please provide more information about the product condition."><button class="btn btn-outline-warning w-100" type="submit">Request more information</button></form><form method="post" action="${returnsBasePath}"><input type="hidden" name="action" value="review"><input type="hidden" name="status" value="REJECTED"><input type="hidden" name="id" value="${returnRequest.id}"><input type="hidden" name="returnMode" value="detail"><input type="text" name="note" class="form-control mb-2" placeholder="Reason for rejection" required><button class="btn btn-outline-danger w-100" type="submit">Reject request</button></form></c:if>
                        <%-- Chỉ khi đã duyệt, Staff mới được xác nhận hàng đã nhận và cộng tồn kho. --%>
                        <c:if test="${returnRequest.status eq 'APPROVED'}"><form method="post" action="${returnsBasePath}"><input type="hidden" name="action" value="receive"><input type="hidden" name="id" value="${returnRequest.id}"><input type="hidden" name="returnMode" value="detail"><textarea name="note" class="form-control mb-2" rows="2" placeholder="Condition on arrival (optional)"></textarea><button class="btn btn-primary w-100" type="submit">Confirm products received</button></form></c:if>
                        <%-- Sau khi nhận hàng, Staff lập đề nghị để Admin duyệt tiền. --%>
                        <c:if test="${returnRequest.status eq 'RECEIVED'}"><form method="post" action="${returnsBasePath}"><input type="hidden" name="action" value="requestRefund"><input type="hidden" name="id" value="${returnRequest.id}"><input type="hidden" name="returnMode" value="detail"><button class="btn btn-primary w-100" type="submit">Submit refund for approval</button></form></c:if>
                        <%-- Đây là quyền riêng của Admin, Staff không thấy nút duyệt tiền. --%>
                        <c:if test="${sessionScope.authRoleName eq 'ADMIN' and returnRequest.status eq 'REFUND_PENDING'}"><form method="post" action="${returnsBasePath}" class="mb-2"><input type="hidden" name="action" value="approveRefund"><input type="hidden" name="id" value="${returnRequest.id}"><input type="hidden" name="returnMode" value="detail"><input type="text" name="note" class="form-control mb-2" placeholder="Approval note (optional)"><button class="btn btn-success w-100" type="submit">Approve refund</button></form><form method="post" action="${returnsBasePath}"><input type="hidden" name="action" value="rejectRefund"><input type="hidden" name="id" value="${returnRequest.id}"><input type="hidden" name="returnMode" value="detail"><input type="text" name="note" class="form-control mb-2" placeholder="Reason for rejection" required><button class="btn btn-outline-danger w-100" type="submit">Reject refund</button></form></c:if>
                        <c:if test="${returnRequest.status eq 'COMPLETED' or returnRequest.status eq 'REJECTED'}"><div class="alert alert-light border mb-0">No more actions are available for this request.</div></c:if>
                    </div></div></div>
                </div>
            </c:otherwise></c:choose>
        </c:when>
        <c:otherwise>
            <div class="page-header"><div><h1 class="page-title"><i class="fa-solid fa-rotate-left"></i>Returns & Refunds</h1><p class="subtext mt-1">Manage customer return requests, refunds, and returned stock.</p></div></div>
            <c:if test="${sessionScope.authRoleName eq 'ADMIN'}"><div class="row g-3 mb-4"><c:forEach var="entry" items="${statusCounts}"><div class="col-sm-6 col-xl-2"><div class="card card-main"><div class="card-body"><div class="text-muted small">${entry.key}</div><div class="fs-3 fw-bold">${entry.value}</div></div></div></div></c:forEach><div class="col-sm-6 col-xl-2"><div class="card card-main"><div class="card-body"><div class="text-muted small">REFUNDED VALUE</div><div class="fs-5 fw-bold"><fmt:formatNumber value="${totalRefunded}" pattern="#,##0"/> VND</div></div></div></div></div></c:if>
            <div class="card card-main mb-4"><div class="card-body p-4"><form class="row g-3 align-items-end" method="get" action="${returnsBasePath}"><div class="col-md-5"><label class="form-label fw-semibold">Keyword</label><input name="keyword" class="form-control" value="${param.keyword}" placeholder="Request code, order code, customer..."></div><div class="col-md-4"><label class="form-label fw-semibold">Status</label><select name="status" class="form-select"><c:forEach var="option" items="${statusOptions}"><option value="${option.key}" ${param.status eq option.key ? 'selected' : ''}>${option.value}</option></c:forEach></select></div><div class="col-md-3"><button class="btn btn-primary me-2" type="submit">Search</button><a class="btn btn-outline-secondary" href="${returnsBasePath}">Reset</a></div></form></div></div>
            <div class="card card-main"><div class="card-body p-0"><c:choose><c:when test="${empty returnRequests}"><div class="empty-state">No return requests found.</div></c:when><c:otherwise><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th class="ps-4">Request</th><th>Customer</th><th>Order</th><th>Type / Reason</th><th>Refund</th><th>Status</th><th>Requested</th><th class="text-end pe-4">Action</th></tr></thead><tbody><c:forEach var="item" items="${returnRequests}"><tr><td class="ps-4"><strong>${item.requestCode}</strong></td><td>${item.customerName}<div class="small text-muted">${item.customerEmail}</div></td><td>${item.orderCode}</td><td>${item.requestType}<div class="small text-muted">${item.reason}</div></td><td><fmt:formatNumber value="${item.refundAmount}" pattern="#,##0"/> VND</td><td><span class="badge rounded-pill text-bg-secondary">${item.status}</span></td><td><fmt:formatDate value="${item.requestedAt}" pattern="dd/MM/yyyy HH:mm"/></td><td class="text-end pe-4"><a class="btn btn-sm btn-outline-primary" href="${returnsBasePath}?action=view&id=${item.id}">View</a></td></tr></c:forEach></tbody></table></div></c:otherwise></c:choose></div></div>
            <c:if test="${sessionScope.authRoleName eq 'ADMIN' and not empty reportRows}"><div class="card card-main mt-4"><div class="card-header"><h2 class="h5 fw-bold mb-0">Returned inventory report</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Product</th><th>SKU</th><th>Returned quantity</th><th>Current stock</th><th>Refund value</th></tr></thead><tbody><c:forEach var="row" items="${reportRows}"><tr><td>${row.productName}</td><td>${row.sku}</td><td>${row.quantityReturned}</td><td>${row.currentStock}</td><td><fmt:formatNumber value="${row.refundAmount}" pattern="#,##0"/> VND</td></tr></c:forEach></tbody></table></div></div></c:if>
        </c:otherwise>
    </c:choose>
</div>
<jsp:include page="/view/admin/common/admin_layout_end.jsp"/>
